### ISSUE TITLE
public key not available

### ISSUE THREAD

**Issue by gisogrimm** [HoerTech-gGmbH/openMHA#55] opened 2022-07-13 12:50 UTC
Err:6 http://apt.hoertech.de jammy InRelease            
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7D6CDF547DA4ABD

This kind of error occurs whenever updating the repository.

**Comment by gisogrimm** [comment] 2022-07-13 12:50
But only in jammy, not in bionic or focal.

**Comment by tobiasherzke** [comment] 2022-07-13 13:10
Cannot reproduce. Last openMHA release was before ubuntu 22.04 was released, therefore no regular openMHA release for ubuntu 22.04 can be installed at the moment. The installation instructions have already been updated in branch development, and following the [latest installation instructions](https://github.com/HoerTech-gGmbH/openMHA/blob/development/INSTALLATION.md) succeeds up to the update from the repository:

```
wget -qO- http://apt.hoertech.de/openmha-packaging.pub | sudo tee /etc/apt/trusted.gpg.d/openmha-packaging.asc
sudo apt-add-repository 'deb [arch=amd64] http://apt.hoertech.de jammy universe'
```
Installing openMHA does not succeed at this point because there are no releases for jammy.

Installing a prerelease version succeeds as per instructions here https://github.com/HoerTech-gGmbH/openMHA/blob/development/PRERELEASE_VERSIONS.md (in addition to the commands above:)

```
sudo apt-add-repository 'deb [arch=amd64] http://aptdev.hoertech.de/ jammy universe'
sudo apt install openmha openmha-examples
```

but this document has formatting errors that should be fixed.

**Comment by tobiasherzke** [comment] 2022-07-13 13:37
Formatting in https://github.com/HoerTech-gGmbH/openMHA/blob/development/PRERELEASE_VERSIONS.md is now fixed.

**Closed as completed by tobiasherzke** 2022-07-13 13:37 UTC
